modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-block-variants/issues" #optional

[[mods]] #mandatory

modId="block_variants" #mandatory
version="2.7" #mandatory
displayName="Block Variants" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-block-variants" #optional
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Barion" #optional
description='''
Adds Variants of Vanilla Blocks that are for some reason missing and more recipes for existing Blocks.
'''
[[dependencies.block_variants]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.block_variants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"