modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/BarionLP/BlockVariants/issues" #optional

[[mods]] #mandatory
    modId="block_variants" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Block Variants" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/vanilla-block-variants" #optional
    logoFile="logo.png" #optional
    #credits="Thanks for this example mod goes to Java" #optional
    authors="Barion" #optional
    description='''Provides you tons of blocks that are missing in vanilla like Polished Diorite Walls and Amethyst Slabs'''

[[dependencies.block_variants]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44.1,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.block_variants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.block_variants]]
    modId="ametrin"
    mandatory=true
    versionRange="[0.0.31,)"
    ordering="NONE"
    side="BOTH"