license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/BlockVariants/issues" #optional

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    updateJSONURL="https://raw.githubusercontent.com/Ametrin-Studios/BlockVariants/main/update.json" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/block-variants" #optional
    logoFile="logo.png" #optional
    #credits="" #optional
    authors="${mod_authors}" #optional
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin"
    type="required"
    versionRange="${ametrin_version_range}"
    ordering="NONE"
    side="BOTH"
